name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: echo "NVM_VERSION=$(cat ${{ github.workspace }}/.nvmrc | xargs)" >> $GITHUB_ENV
      - name: Use Node.js ${{ env.NVM_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NVM_VERSION }}
      - run: npm ci
        working-directory: ${{ github.workspace }}
      - name: Build
        run: npm run build --if-present
        working-directory: ${{ github.workspace }}

